import React, { Component } from "react";
import { LoginRegisterForm } from "./components/Loginregister";
import {
  BrowserRouter as Router,
  Route,
  Redirect,
  Switch,
} from "react-router-dom";
import { Main } from "./Main";
import { User } from "./User";

export const Routing = ({ loggedIn, changeLoginState }) => (
  <Router>
    <Switch>
      <PrivateRoute
        path="/app"
        component={() => <Main changeLoginState={changeLoginState} />}
        loggedIn={loggedIn}
      />
      <PrivateRoute
        path="/user/:username"
        component={(props) => (
          <User {...props} changeLoginState={changeLoginState} />
        )}
        loggedIn={loggedIn}
      />
      <LoginRoute
        exact
        path="/"
        component={() => (
          <LoginRegisterForm changeLoginState={changeLoginState} />
        )}
        loggedIn={loggedIn}
      />
      <Route component={NotFound} />
    </Switch>
  </Router>
);

const PrivateRoute = ({ component: Component, ...rest }) => (
  <Route
    {...rest}
    render={(props) =>
      rest.loggedIn === true ? (
        <Component {...props} />
      ) : (
        <Redirect
          to={{
            pathname: "/",
            state: { from: props.location }, // keep track of the url before redirect to main page. Its holds the last matched path in the props.location field generated by React Router
          }}
        />
      )
    }
  />
);

const LoginRoute = ({ component: Component, ...rest }) => (
  <Route
    {...rest}
    render={(props) =>
      rest.loggedIn === false ? (
        <Component {...props} />
      ) : (
        <Redirect
          to={{
            pathname:
              typeof props.location.state !== typeof undefined
                ? props.location.state.from.pathname
                : "/app",
          }}
        />
      )
    }
  />
);

const NotFound = () => {
  <Redirect to="/" />;
};
